name: Sync Trello and GH Issues
on:
  schedule:
    - cron:  '*/30 * * * *'
jobs:
  updateFork:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: andrenatal/ghactions
    - name: Run script
      run: | 
       python trello_gh_sync.py
