name: Sync Trello and GH Issues
on:
  schedule:
    - cron:  '0 * * * *'
jobs:
  syncTrelloAndGH:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: andrenatal/ghactions
    - name: Sync extension
      env:
        TRELLO_KEY: ${{ secrets.TRELLO_KEY }}
        TRELLO_TOKEN: ${{ secrets.TRELLO_TOKEN }}
        CHECKITEMS_ID: ${{ secrets.CHECKITEMS_ID_EXT }}
        CARD_ID: ${{ secrets.CARD_ID_EXT }}
        URL_ISSUES: ${{ secrets.URL_ISSUES_EXT }}
        GH_TOKEN: ${{ secrets.PAT }}
      run: | 
       python trello_gh_sync.py
    - name: Sync Bergamot Translator Mozilla
      env:
        TRELLO_KEY: ${{ secrets.TRELLO_KEY }}
        TRELLO_TOKEN: ${{ secrets.TRELLO_TOKEN }}
        CHECKITEMS_ID: ${{ secrets.CHECKITEMS_ID_BT_MOZ }}
        CARD_ID: ${{ secrets.CARD_ID_BT_MOZ }}
        URL_ISSUES: ${{ secrets.URL_ISSUES_BT_MOZ }}
        GH_TOKEN: ${{ secrets.PAT }}
      run: | 
       python trello_gh_sync.py
    - name: Sync Bergamot Translator Browsermt
      env:
        TRELLO_KEY: ${{ secrets.TRELLO_KEY }}
        TRELLO_TOKEN: ${{ secrets.TRELLO_TOKEN }}
        CHECKITEMS_ID: ${{ secrets.CHECKITEMS_ID_BT_BMT }}
        CARD_ID: ${{ secrets.CARD_ID_BT_BMT }}
        URL_ISSUES: ${{ secrets.URL_ISSUES_BT_BMT }}
        GH_TOKEN: ${{ secrets.PAT }}
      run: | 
       python trello_gh_sync.py
